#!/bin/bash
# vim: noet sw=8 ts=8
# Simple script to extract text and images from a word document
# e.g. screenshot.doc ;-)
# Requires abiword and wv
ME=`basename "${0}"`
USAGE="usage: ${ME} [-e editor] [-v viewer] <docfile> <outdir>"
while getopts e:v:xz c; do
	case "${c}" in
	e)	VISUAL="${OPTARG}";;
	v)	VIEWER="${OPTARG}";;
	x)	set -x;;
	z)	set -e;;
	*)	echo "${USAGE}" >&2; exit 1;;
	esac
done
shift `expr "${OPTIND}" - 1`
if [ $# -ne 2 ];then
	echo "${USAGE}" >&2
	exit 1
fi
DOCFILE="${1}"
OUTDIR="${2}"
BN=$(basename -- "${DOCFILE}")
EXT="${DOCFILE##*.}"
UUID=$(uuidgen)
TMPFILE=/tmp/"${UUID}."${EXT}""
cp -- "${DOCFILE}" "${TMPFILE}"
abiword --to=sxw -- "${TMPFILE}"
if unzip -l /tmp/"${UUID}".sxw | grep Pictures
then
  IMAGEPATH=Pictures
elif unzip -l /tmp/"${UUID}".sxw | grep word
then
  IMAGEPATH='word/media'
fi
unzip -q -d -- "${OUTDIR}" /tmp/$$.sxw "${IMAGEPATH}"/*
abiword --to=txt --to-name="${OUTDIR}"/text -- "${TMPFILE}"
rm -f -- "${TMPFILE}"
ls -R -- "${OUTDIR}"
${VIEWER:-eog} -- "${OUTDIR}"/"${IMAGEPATH}"/ &
${VISUAL:-"${EDITOR:-gedit}"} -- "${OUTDIR}"/text &
unzip -q -d -- "${OUTDIR}" /tmp/"${UUID}".sxw "${IMAGEPATH}"/*
abiword --to=txt --to-name="${OUTDIR}"/text -- "${TMPFILE}"
rm -- "${TMPFILE}"
ls -R -- "${OUTDIR}"
if [ -n "${VIEWER}" ];
then
    eval "${VIEWER}" -- "${OUTDIR}"/"${IMAGEPATH}"/ &
fi
if [ -n "${TXTVIEWER}" ];
then
    eval "${TXTVIEWER}" -- "${OUTDIR}"/text &
fi
