#!/bin/bash
# vim: noet sw=8 ts=8
# Simple script to extract text and images from a word document
# e.g. screenshot.doc ;-)
# Requires abiword and wv
set -e
ME=`basename "${0}"`
USAGE="usage: ${ME} [-e editor] [-v viewer] <docfile> <outdir>"
while getopts e:v:xz c; do
	case "${c}" in
	e)	VISUAL="${OPTARG}";;
	v)	VIEWER="${OPTARG}";;
	x)	set -x;;
	z)	set +e;;
	*)	echo "${USAGE}" >&2; exit 1;;
	esac
done
shift `expr "${OPTIND}" - 1`
if [ $# -ne 2 ];then
	echo "${USAGE}" >&2
	exit 1
fi
DOCFILE="${1}"
OUTDIR="${2}"
BN=${DOCFILE##*/}
FN=${BN%%.*}
mkdir -p "${OUTDIR}/x-files" "${OUTDIR}/tmp"
abiword --to=txt --to-name="${OUTDIR}/${FN}.txt" "${DOCFILE}"
SXWFILE="${OUTDIR}/tmp/${FN}.$$.sxw"
trap "rm -f -- ${SWXFILE}" 0
abiword --to=sxw --to-name="${SXWFILE}" "${DOCFILE}"
unzip -d "${OUTDIR}/x-files/" "${SXWFILE}"
trap "" 0
